/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: msg.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C_NO_DEPRECATED
#define PROTOBUF_C_NO_DEPRECATED
#endif

#include "msg.pb-c.h"
void   sub_msg__init
                     (SubMsg         *message)
{
  static SubMsg init_value = SUB_MSG__INIT;
  *message = init_value;
}
size_t sub_msg__get_packed_size
                     (const SubMsg *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &sub_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sub_msg__pack
                     (const SubMsg *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &sub_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sub_msg__pack_to_buffer
                     (const SubMsg *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &sub_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SubMsg *
       sub_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SubMsg *)
     protobuf_c_message_unpack (&sub_msg__descriptor,
                                allocator, len, data);
}
void   sub_msg__free_unpacked
                     (SubMsg *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &sub_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   main_msg__init
                     (MainMsg         *message)
{
  static MainMsg init_value = MAIN_MSG__INIT;
  *message = init_value;
}
size_t main_msg__get_packed_size
                     (const MainMsg *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &main_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t main_msg__pack
                     (const MainMsg *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &main_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t main_msg__pack_to_buffer
                     (const MainMsg *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &main_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MainMsg *
       main_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MainMsg *)
     protobuf_c_message_unpack (&main_msg__descriptor,
                                allocator, len, data);
}
void   main_msg__free_unpacked
                     (MainMsg *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &main_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor sub_msg__field_descriptors[3] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SubMsg, name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "age",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    PROTOBUF_C_OFFSETOF(SubMsg, has_age),
    PROTOBUF_C_OFFSETOF(SubMsg, age),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "array",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT32,
    PROTOBUF_C_OFFSETOF(SubMsg, n_array),
    PROTOBUF_C_OFFSETOF(SubMsg, array),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sub_msg__field_indices_by_name[] = {
  1,   /* field[1] = age */
  2,   /* field[2] = array */
  0,   /* field[0] = name */
};
static const ProtobufCIntRange sub_msg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor sub_msg__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "SubMsg",
  "SubMsg",
  "SubMsg",
  "",
  sizeof(SubMsg),
  3,
  sub_msg__field_descriptors,
  sub_msg__field_indices_by_name,
  1,  sub_msg__number_ranges,
  (ProtobufCMessageInit) sub_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor main_msg__field_descriptors[3] =
{
  {
    "req_sub",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(MainMsg, req_sub),
    &sub_msg__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "opt_sub",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(MainMsg, opt_sub),
    &sub_msg__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rep_sub",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(MainMsg, n_rep_sub),
    PROTOBUF_C_OFFSETOF(MainMsg, rep_sub),
    &sub_msg__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned main_msg__field_indices_by_name[] = {
  1,   /* field[1] = opt_sub */
  2,   /* field[2] = rep_sub */
  0,   /* field[0] = req_sub */
};
static const ProtobufCIntRange main_msg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor main_msg__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "MainMsg",
  "MainMsg",
  "MainMsg",
  "",
  sizeof(MainMsg),
  3,
  main_msg__field_descriptors,
  main_msg__field_indices_by_name,
  1,  main_msg__number_ranges,
  (ProtobufCMessageInit) main_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
